spring:
  config:
    activate:
      on-profile: dev

  # Base de datos principal para desarrollo (local)
  datasource:
    url: jdbc:mysql://${app.database.host}:${app.database.port}/${app.database.nombreBD}
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA/Hibernate para desarrollo
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

# Configuración específica de desarrollo
server:
  port: 8080

# Configuración Host y puerto y nombre de BD separados para facilitar su uso
app:
  database:
    host: 127.0.0.1
    port: 3306
    nombreBD : billing_republicadominicana

