package org.dcoronado.WebServiceDGIIRepublicaDominicana.FacturacionElectronica.Comprobante.Domain.Validator.TiposComprobantes;

public class FacturaConsumoValidatorExtendida extends FacturaConsumoValidator {

}
